import { FugueTree } from "../../../dts/index.js";
import { FugueMessage } from "../../../types/index.js";
import { logger } from "../../../utils/logging.js";
import { OperationType } from "../../Actions/index.js";
import { Registry } from "../Registry/index.js";
import { logicalTimeOf } from "./CausalOrder.js";
import { classifyConflict } from "./ConflictClassifier.js";
import { ConflictHandler, ConflictType, NidhoggrOptions, NodeHistoryEntry, TxnSnapshot } from "./types.js";

interface PendingTxn {
    txnId: string;
    opType: OperationType;
    msgs: FugueMessage[];
    arrivedAt: number;
}

interface AppliedTxn {
    txn: PendingTxn;
    registryStateBefore: ReturnType<Registry["save"]>;
    appliedAt: number;
}

/**
 * Effects recevied COAST-tagged FugueMessages, generated by Ratatoskr, applying them to remote replicas and detecting and handling
 * conflicts as they arise.
 */
export class Nidhoggr {
    fugue: FugueTree;
    registry: Registry;
    // Map of txnId to buffered messages for txns that haven't yet been fully received.
    private pendingTxns: Map<string, PendingTxn> = new Map();
    // History of the most recent operation observed on each node, used for conflict detection. Accessed by nodeKey.
    private nodeHistory: Map<string, NodeHistoryEntry> = new Map();
    private history: AppliedTxn[] = [];
    // The time to live (milliseconds) for pending txns before we consider them stale and apply whatever we have.
    // This is to prevent indefinitely buffering incomplete txns if some messages are lost.
    private readonly txnTtlMs: number;
    // Optional conflict handler callback, invoked when a potential conflict is detected. If not provided, the user is only notified of conflicts
    private onConflict: ConflictHandler | null;

    constructor(fugue: FugueTree, registry: Registry, options?: NidhoggrOptions) {
        this.fugue = fugue;
        this.registry = registry;
        this.txnTtlMs = options?.txnTtlMs ?? 10_000;
        this.onConflict = options?.onConflict ?? null;
    }

    /**
     * Takes in a FugueMessages, applies any that are ready (i.e. non-COAST messages and COAST txns for which we've received all parts),
     * buffers the rest, and returns the list of messages that were applied as a result of this call.
     * @param msgs - A FugueMessage or array of FugueMessages received from Ratatoskr.
     * @returns An array of FugueMessages that were applied as a result of this call.
     */
    consume(msgs: FugueMessage | FugueMessage[]): FugueMessage[] {
        // First remove any expired txns to prevent unbounded growth
        // of the pendingTxns map and to ensure we don't indefinitely wait for missing messages.
        this.removeExpiredTxns();

        const all = Array.isArray(msgs) ? msgs : [msgs];

        // Filter to only messages from remote replicas, since we don't want to process our own local operations.
        const remote = all.filter((m) => m.replicaId !== this.fugue.replicaId());

        const plain: FugueMessage[] = [];
        const grouped = new Map<string, FugueMessage[]>();

        // Group messages by their coastTxId, which identifies which txn they belong to.
        // Messages without a coastTxId can be applied immediately.
        for (const msg of remote) {
            if (msg.coastTxId) {
                const group = grouped.get(msg.coastTxId) ?? [];
                group.push(msg);
                grouped.set(msg.coastTxId, group);
            } else {
                plain.push(msg);
            }
        }

        const applied: FugueMessage[] = [];

        // Apply plain messages immediately
        if (plain.length > 0) {
            applied.push(...this.fugue.effect(plain));
        }

        // Route COAST txns through the buffered pipeline.
        for (const [txId, txMsgs] of grouped) {
            applied.push(...this.handleTxn(txId, txMsgs));
        }

        return applied;
    }

    /**
     * Handles a single COAST txn, which may consist of one or more messages. If we've received all messages for this txn,
     * it applies the messagse and returns the resulting FugueMessages.
     * @param txId - The COAST txn ID that identifies which messages belong to the same txn.
     * @param msgs - The list of messages that belong to this txn.
     */
    private handleTxn(txId: string, msgs: FugueMessage[]): FugueMessage[] {
        // Determine the operation type of this txn. We assume all messages in the same txn have the same opType,
        // so we can just look at the first one.
        const firstMsg = msgs[0];
        // If the first message doesn't have an opType, we can't process this txn, so we throw an error.
        // This shouldn't happen if Ratatoskr is generating messages correctly.
        if (!firstMsg.coastOpType)
            throw new Error(`Received COAST message without coastOpType: ${JSON.stringify(firstMsg)}`);
        const opType = firstMsg.coastOpType;

        // Merge with any buffered messages for this txId.
        const existing = this.pendingTxns.get(txId);
        const allMsgs = existing ? [...existing.msgs, ...msgs] : [...msgs];

        // Create a new pending txn object with the merged messages and the earliest arrival time.
        const txn: PendingTxn = {
            txnId: txId,
            opType,
            msgs: allMsgs,
            arrivedAt: existing?.arrivedAt ?? Date.now(),
        };

        // If we have all the messages for this txn, apply it. Otherwise, buffer it until we receive the rest.
        if (this.isTxnComplete(txn)) {
            this.pendingTxns.delete(txId);
            return this.applyTxn(txn);
        } else {
            this.pendingTxns.set(txId, txn);
            return [];
        }
    }

    /**
     * Determines whether we have received all messages for a given txn.
     * @param txn - The pending txn to check for completeness.
     * @returns True if we have received all messages for this txn and it is ready to be applied, false if we are still waiting for more messages.
     */
    private isTxnComplete(txn: PendingTxn): boolean {
        // For MOVE and UPDATE txns, we expect at least one INSERT and one DELETE message,
        // but we may not know the exact counts upfront, so we check for the presence of messages with
        // coastExpectedInsertCount and coastExpectedDeleteCount to determine if we have all messages.
        if (txn.opType === "MOVE" || txn.opType === "UPDATE") {
            const insertMsgs = txn.msgs.filter((m) => m.coastOpPart === "INSERT");
            const deleteMsgs = txn.msgs.filter((m) => m.coastOpPart === "DELETE");
            const ref = txn.msgs.find((m) => m.coastExpectedInsertCount && m.coastExpectedDeleteCount);
            if (!ref) {
                // We don't have concrete counts of the expected messages so just expect at least one INSERT and one DELETE
                // which is the minimum for a MOVE or UPDATE txn to be valid.
                return insertMsgs.length > 0 && deleteMsgs.length > 0;
            }
            // At this point we've found a message in the txn that includes the expected counts of INSERTs and DELETEs,
            // so we can use those counts to determine if we've received all messages for this txn.
            return (
                insertMsgs.length >= ref.coastExpectedInsertCount! && deleteMsgs.length >= ref.coastExpectedDeleteCount!
            );
        }
        return txn.msgs.length > 0;
    }

    /**
     * Applies the messages of a completed txn to the FugueTree
     * @param txn - The pending txn to apply.
     * @return An array of FugueMessages that were the result of applying this txn.
     */
    private applyTxn(txn: PendingTxn): FugueMessage[] {
        const incomingTime = logicalTimeOf(txn.msgs);

        let msgs: FugueMessage[] = [];
        const laterTxns = this.history.filter(
            (h) => h.txn.txnId !== txn.txnId && logicalTimeOf(h.txn.msgs) > incomingTime,
        );

        if (laterTxns.length > 0) {
            logger.debug(
                `[Nidhoggr] Received out-of-order txn ${txn.opType} ${txn.txnId} with logical time ${incomingTime}. Reverting and re-applying ${laterTxns.length} later txns.`,
            );
            for (const later of laterTxns.reverse()) {
                logger.debug(
                    `[Nidhoggr] Reverting ${later.txn.opType} txn ${later.txn.txnId} to apply earlier txn ${txn.opType} ${txn.txnId}`,
                );
                this.fugue.undo(later.txn.msgs);
            }

            msgs = this.executeTxn(txn);

            for (const later of laterTxns) {
                logger.debug(
                    `[Nidhoggr] Re-applying ${later.txn.opType} txn ${later.txn.txnId} after applying earlier txn ${txn.opType} ${txn.txnId}`,
                );
                msgs.push(...this.executeTxn(later.txn));
            }
        } else {
            logger.debug(
                `[Nidhoggr] Applying in-order txn ${txn.opType} ${txn.txnId} with logical time ${incomingTime}`,
            );
            msgs = this.executeTxn(txn);
        }

        this.history.push({
            txn,
            registryStateBefore: this.registry.save(),
            appliedAt: Date.now(),
        });
        this.history.sort((a, b) => logicalTimeOf(a.txn.msgs) - logicalTimeOf(b.txn.msgs));

        return msgs;
    }

    private executeTxn(txn: PendingTxn): FugueMessage[] {
        // Before applying the txn, we perform conflict detection to see if this txn conflicts with
        // any prior operations we've seen on the same node.
        this.detectConflicts(txn);
        logger.debug(`Pending txns -> ${[...this.pendingTxns.keys()].join(", ")}`);

        switch (txn.opType) {
            case "ADD":
                return this.handleAdd(txn);
            case "DELETE":
                return this.handleDelete(txn);
            case "MOVE":
                return this.handleMove(txn);
            case "UPDATE":
                return this.handleUpdate(txn);
            default:
                return [];
        }
    }

    /**
     * Helper function to find the first applied message in a txn, which we can use as a reference point for registering the node in the registry.
     * @param txn - The pending txn to search through.
     * @returns The FugueMessage with the smallest counter value among the messages in this txn or null if there are no messages.
     */
    private findFirstAppliedMsg(msgs: FugueMessage[]): FugueMessage | null {
        let firstApplied: FugueMessage | null = null;
        let minCounter = Infinity;
        for (const msg of msgs) {
            if (msg.id.counter < minCounter) {
                minCounter = msg.id.counter;
                firstApplied = msg;
            }
        }
        return firstApplied;
    }

    /**
     * Handle an ADD txn by applying its messages to the FugueTree.
     * @param txn - The pending txn to apply.
     * @returns An array of FugueMessages that were the result of applying this txn.
     */
    private handleAdd(txn: PendingTxn): FugueMessage[] {
        // First we effect the txn's messages
        const applied = this.fugue.effect(txn.msgs);

        // Then we update the registry with the new node if it doesn't already exist.
        // We can have multiple ADD txns for the same nodeKey if multiple users are concurrently adding the same node,
        // but we only want to register the first one since they should all be adding the same content at the same position.
        if (txn.msgs.length > 0) {
            const nodeKey = txn.msgs[0].coastNodeKey!;
            if (applied.length > 0) {
                if (!this.registry.get(nodeKey)) {
                    // Find the minimum counter among the applied ADD messages, which should correspond to the first message that added this node.
                    let firstApplied = this.findFirstAppliedMsg(applied);

                    if (firstApplied) {
                        this.registry.register(nodeKey, {
                            startId: firstApplied.id,
                            length: txn.msgs.length,
                        });
                    }
                }

                // Record this operation in the node history for future conflict detection.
                this.recordHistory(txn);
            }
        }

        return applied;
    }

    /**
     * Handle a DELETE txn by applying its messages to the FugueTree and updating the registry accordingly.
     * @param txn - The pending txn to apply.
     * @returns An array of FugueMessages that were the result of applying this txn.
     */
    private handleDelete(txn: PendingTxn): FugueMessage[] {
        // First we effect the txn's messages
        const applied = this.fugue.effect(txn.msgs);

        // Then we delete the node from the registry if it was successfully deleted.
        // We can have multiple DELETE txns for the same nodeKey
        if (applied.length > 0) {
            const nodeKey = txn.msgs[0].coastNodeKey!;
            this.registry.delete(nodeKey);
            this.recordHistory(txn);
        }

        return applied;
    }

    /**
     * Handle a MOVE txn by applying its messages to the FugueTree and updating the registry accordingly.
     * @param txn - The pending txn to apply.
     * @returns An array of FugueMessages that were the result of applying this txn.
     */
    private handleMove(txn: PendingTxn): FugueMessage[] {
        // A MOVE txn consists of DELETE messages for the old position and INSERT messages for the new position.
        const insertMsgs = txn.msgs.filter((m) => m.coastOpPart === "INSERT");
        const deleteMsgs = txn.msgs.filter((m) => m.coastOpPart === "DELETE");

        // Like with Ratatoskr's handleMove function we apply the INSERTs before the DELETEs to prevent loss
        // of content during the move.
        const appliedInserts = this.fugue.effect(insertMsgs);
        const appliedDeletes = this.fugue.effect(deleteMsgs);

        const applied = [...appliedInserts, ...appliedDeletes];

        if (appliedInserts.length > 0) {
            const nodeKey = txn.msgs[0].coastNodeKey!;

            const firstInsert = this.findFirstAppliedMsg(appliedInserts);
            if (firstInsert) {
                this.registry.update(nodeKey, {
                    startId: firstInsert.id,
                });
            }

            this.recordHistory(txn);
        }

        return applied;
    }

    /**
     * Handle an UPDATE txn by applying its messages to the FugueTree and updating the registry accordingly.
     * @param txn - The pending txn to apply.
     * @returns An array of FugueMessages that were the result of applying this txn.
     */
    private handleUpdate(txn: PendingTxn): FugueMessage[] {
        // An UPDATE txn consists of DELETE messages for the old content and INSERT messages for the new content at the same position.
        const deleteMsgs = txn.msgs.filter((m) => m.coastOpPart === "DELETE");
        const insertMsgs = txn.msgs.filter((m) => m.coastOpPart === "INSERT");

        // Like with Ratatoskr's handleUpdate function we apply the DELETEs before the INSERTs because we don't
        // care about the old content being lost since it's being replaced
        const appliedDeletes = this.fugue.effect(deleteMsgs);
        const appliedInserts = this.fugue.effect(insertMsgs);

        const applied = [...appliedDeletes, ...appliedInserts];

        if (appliedInserts.length > 0) {
            const nodeKey = txn.msgs[0].coastNodeKey!;
            const firstInsert = this.findFirstAppliedMsg(appliedInserts);

            if (firstInsert) {
                this.registry.update(nodeKey, {
                    startId: firstInsert.id,
                    length: insertMsgs.length,
                });
            }

            this.recordHistory(txn);
        }

        return applied;
    }

    /**
     * Detects potential conflicts between the given txn and prior operations on the same node, and invokes the conflict handler if a potential conflict is detected.
     * @param txn - The pending txn for which to detect conflicts.
     */
    private detectConflicts(txn: PendingTxn) {
        // If we don't have a conflict handler, we can skip the conflict detection logic entirely since the user doesn't want to be notified of conflicts.
        if (!this.onConflict) return;

        const nodeKey = txn.msgs[0]?.coastNodeKey;
        if (!nodeKey) return;

        const prior = this.nodeHistory.get(nodeKey);
        // If it's the first time we've seen an operation on this node, there's no possibility of conflict, so we can skip the rest of the checks.
        if (!prior) return;

        // Classify the type of conflict (if any) between this txn and the prior operation on the same node, and invoke the conflict handler if a conflict is detected.
        const conflict = classifyConflict(
            nodeKey,
            prior,
            { txnId: txn.txnId, opType: txn.opType, msgs: txn.msgs },
            this.registry.get(nodeKey) !== undefined,
        );

        if (conflict) {
            this.onConflict(conflict);
        }
    }

    /**
     * Records the given txn in the node history for future conflict detection.
     * @param txn - The pending txn to record in the history.
     */
    private recordHistory(txn: PendingTxn): void {
        const nodeKey = txn.msgs[0]?.coastNodeKey;
        if (!nodeKey) return;

        const entry: NodeHistoryEntry = {
            userIdentity: txn.msgs[0].userIdentity,
            txnId: txn.txnId,
            opType: txn.opType,
            replicaId: txn.msgs[0].replicaId,
            logicalTime: logicalTimeOf(txn.msgs),
            appliedAt: Date.now(),
        };

        this.nodeHistory.set(nodeKey, entry);
    }

    /**
     * Removes any pending txns that have been buffered for longer than the configured time to live,
     * applying whatever messages we have for those txns to prevent indefinite buffering in the case of lost messages.
     * This is a best effort mechanism to handle message loss and ensure that we don't end up with an ever-growing buffer of pending txns if some messages never arrive.
     * The assumption is that if we've been waiting for a txn for a long time, it's better to apply whatever we have and potentially have some
     * inconsistencies than to wait indefinitely and never apply anything from that txn.
     */
    private removeExpiredTxns() {
        const now = Date.now();
        for (const [txId, tx] of this.pendingTxns) {
            if (now - tx.arrivedAt > this.txnTtlMs) {
                logger.warn(
                    `[Nidhoggr] Evicting stale COAST txn ${txId} (opType=${tx.opType}, age=${now - tx.arrivedAt}ms). Applying with partial messages.`,
                );
                this.pendingTxns.delete(txId);
                // Apply whatever we have
                this.fugue.effect(tx.msgs);
            }
        }
    }

    /**
     * Returns the number of pending txns that are currently buffered and waiting for more messages before they can be applied.
     * @returns The number of pending txns in the buffer.
     */
    numberPending(): number {
        return this.pendingTxns.size;
    }

    /**
     * Generate a snapshot of the current pending txns, including their txnId, opType, number of messages received so far,
     * and age in milliseconds since we first started receiving messages for that txn.
     * @returns An array of TxnSnapshot objects representing the current pending txns in the buffer.
     */
    pendingSnapshot(): TxnSnapshot[] {
        const now = Date.now();
        return [...this.pendingTxns.values()].map((txn) => ({
            txnId: txn.txnId,
            opType: txn.opType,
            msgCount: txn.msgs.length,
            ageMs: now - txn.arrivedAt,
        })) as TxnSnapshot[];
    }
}
